2024-04-09 22:11:37,336 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-09 22:11:37,336 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Configure stats pid to 107058
2024-04-09 22:11:37,337 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Loading settings from /home/russellsb/.config/wandb/settings
2024-04-09 22:11:37,337 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/settings
2024-04-09 22:11:37,337 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-09 22:11:37,338 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-09 22:11:37,338 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 22:11:37,339 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 22:11:37,340 INFO    MainThread:107058 [wandb_init.py:_log_setup():521] Logging user logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240409_221137-yz46dnbh/logs/debug.log
2024-04-09 22:11:37,340 INFO    MainThread:107058 [wandb_init.py:_log_setup():522] Logging internal logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240409_221137-yz46dnbh/logs/debug-internal.log
2024-04-09 22:11:37,341 INFO    MainThread:107058 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f8325c21420>
2024-04-09 22:11:37,342 INFO    MainThread:107058 [wandb_init.py:init():561] calling init triggers
2024-04-09 22:11:37,342 INFO    MainThread:107058 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-09 22:11:37,342 INFO    MainThread:107058 [wandb_init.py:init():611] starting backend
2024-04-09 22:11:37,343 INFO    MainThread:107058 [wandb_init.py:init():615] setting up manager
2024-04-09 22:11:37,348 INFO    MainThread:107058 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-09 22:11:37,349 INFO    MainThread:107058 [wandb_init.py:init():623] backend started and connected
2024-04-09 22:11:37,359 INFO    MainThread:107058 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-09 22:11:37,360 INFO    MainThread:107058 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-09 22:11:37,360 INFO    MainThread:107058 [wandb_init.py:init():715] updated telemetry
2024-04-09 22:11:37,372 INFO    MainThread:107058 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-09 22:11:37,853 INFO    MainThread:107058 [wandb_run.py:_on_init():2357] communicating current version
2024-04-09 22:11:38,021 INFO    MainThread:107058 [wandb_run.py:_on_init():2366] got version response 
2024-04-09 22:11:38,021 INFO    MainThread:107058 [wandb_init.py:init():799] starting run threads in backend
2024-04-09 22:11:38,160 INFO    MainThread:107058 [wandb_run.py:_console_start():2335] atexit reg
2024-04-09 22:11:38,160 INFO    MainThread:107058 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-09 22:11:38,161 INFO    MainThread:107058 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-09 22:11:38,161 INFO    MainThread:107058 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-09 22:11:38,162 INFO    MainThread:107058 [wandb_init.py:init():842] run started, returning control to user process
2024-04-09 22:11:38,163 INFO    MainThread:107058 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-09 22:11:38,163 INFO    MainThread:107058 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-09 22:11:40,358 INFO    MainThread:107058 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-09 22:11:40,516 INFO    MainThread:107058 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-09 22:11:40,517 INFO    MainThread:107058 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-09 22:12:01,296 INFO    MainThread:107058 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-09 22:12:01,302 INFO    MainThread:107058 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-09 22:12:01,302 INFO    MainThread:107058 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-09 22:12:01,916 INFO    MainThread:107058 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-09 22:12:01,982 INFO    MainThread:107058 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-09 22:12:01,982 INFO    MainThread:107058 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-09 22:12:02,846 INFO    MainThread:107058 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-09 22:12:02,898 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-09 22:12:02,898 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Configure stats pid to 107058
2024-04-09 22:12:02,899 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Loading settings from /home/russellsb/.config/wandb/settings
2024-04-09 22:12:02,899 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/settings
2024-04-09 22:12:02,900 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-09 22:12:02,900 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-09 22:12:02,901 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 22:12:02,901 INFO    MainThread:107058 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 22:12:02,902 INFO    MainThread:107058 [wandb_init.py:_log_setup():521] Logging user logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240409_221202-5f9u6d0f/logs/debug.log
2024-04-09 22:12:02,902 INFO    MainThread:107058 [wandb_init.py:_log_setup():522] Logging internal logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240409_221202-5f9u6d0f/logs/debug-internal.log
2024-04-09 22:12:02,903 INFO    MainThread:107058 [wandb_init.py:init():561] calling init triggers
2024-04-09 22:12:02,903 INFO    MainThread:107058 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-09 22:12:02,904 INFO    MainThread:107058 [wandb_init.py:init():586] re-initializing run, found existing run on stack: yz46dnbh
2024-04-09 22:12:02,906 INFO    MainThread:107058 [wandb_run.py:_finish():2064] finishing run russellsb/x-ray-chest-disease-classification/yz46dnbh
2024-04-09 22:12:02,907 ERROR   MainThread:107058 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-09 22:12:02,908 INFO    MainThread:107058 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-09 22:12:02,908 INFO    MainThread:107058 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-04-09 22:12:02,909 INFO    MainThread:107058 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-09 22:12:02,910 INFO    MainThread:107058 [wandb_run.py:_restore():2287] restore
2024-04-09 22:12:02,910 INFO    MainThread:107058 [wandb_run.py:_restore():2293] restore done
2024-04-09 22:12:07,578 INFO    MainThread:107058 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-09 22:12:07,578 INFO    MainThread:107058 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-09 22:12:07,589 INFO    MainThread:107058 [wandb_run.py:_footer_sync_info():3895] logging synced files
