2024-04-08 14:05:10,623 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-08 14:05:10,624 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Configure stats pid to 465542
2024-04-08 14:05:10,625 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Loading settings from /home/russellsb/.config/wandb/settings
2024-04-08 14:05:10,625 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/settings
2024-04-08 14:05:10,626 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-08 14:05:10,627 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-08 14:05:10,627 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-08 14:05:10,628 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-08 14:05:10,628 INFO    MainThread:465542 [wandb_init.py:_log_setup():521] Logging user logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240408_140510-8rfdnvle/logs/debug.log
2024-04-08 14:05:10,629 INFO    MainThread:465542 [wandb_init.py:_log_setup():522] Logging internal logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240408_140510-8rfdnvle/logs/debug-internal.log
2024-04-08 14:05:10,629 INFO    MainThread:465542 [wandb_init.py:init():561] calling init triggers
2024-04-08 14:05:10,630 INFO    MainThread:465542 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-08 14:05:10,630 INFO    MainThread:465542 [wandb_init.py:init():586] re-initializing run, found existing run on stack: dfogpjdb
2024-04-08 14:05:10,633 INFO    MainThread:465542 [wandb_run.py:_finish():2064] finishing run russellsb/x-ray-chest-disease-classification/dfogpjdb
2024-04-08 14:05:10,634 ERROR   MainThread:465542 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-08 14:05:10,635 INFO    MainThread:465542 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-08 14:05:10,636 INFO    MainThread:465542 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-04-08 14:05:10,636 INFO    MainThread:465542 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-08 14:05:10,638 INFO    MainThread:465542 [wandb_run.py:_restore():2287] restore
2024-04-08 14:05:10,638 INFO    MainThread:465542 [wandb_run.py:_restore():2293] restore done
2024-04-08 14:05:17,199 INFO    MainThread:465542 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-08 14:05:17,200 INFO    MainThread:465542 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-08 14:05:17,214 INFO    MainThread:465542 [wandb_run.py:_footer_sync_info():3895] logging synced files
2024-04-08 14:05:17,344 INFO    MainThread:465542 [wandb_init.py:init():611] starting backend
2024-04-08 14:05:17,345 INFO    MainThread:465542 [wandb_init.py:init():615] setting up manager
2024-04-08 14:05:17,351 INFO    MainThread:465542 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-08 14:05:17,351 INFO    MainThread:465542 [wandb_init.py:init():623] backend started and connected
2024-04-08 14:05:17,362 INFO    MainThread:465542 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-08 14:05:17,362 INFO    MainThread:465542 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-08 14:05:17,362 INFO    MainThread:465542 [wandb_init.py:init():715] updated telemetry
2024-04-08 14:05:17,376 INFO    MainThread:465542 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-08 14:05:18,678 INFO    MainThread:465542 [wandb_run.py:_on_init():2357] communicating current version
2024-04-08 14:05:18,781 INFO    MainThread:465542 [wandb_run.py:_on_init():2366] got version response 
2024-04-08 14:05:18,781 INFO    MainThread:465542 [wandb_init.py:init():799] starting run threads in backend
2024-04-08 14:05:18,951 INFO    MainThread:465542 [wandb_run.py:_console_start():2335] atexit reg
2024-04-08 14:05:18,951 INFO    MainThread:465542 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-08 14:05:18,951 INFO    MainThread:465542 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-08 14:05:18,952 INFO    MainThread:465542 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-08 14:05:18,955 INFO    MainThread:465542 [wandb_init.py:init():842] run started, returning control to user process
2024-04-08 14:15:32,353 INFO    MainThread:465542 [wandb_run.py:_finish():2064] finishing run russellsb/x-ray-chest-disease-classification/8rfdnvle
2024-04-08 14:15:32,354 INFO    MainThread:465542 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-08 14:15:32,355 INFO    MainThread:465542 [wandb_run.py:_restore():2287] restore
2024-04-08 14:15:32,355 INFO    MainThread:465542 [wandb_run.py:_restore():2293] restore done
2024-04-08 14:15:37,387 INFO    MainThread:465542 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-08 14:15:37,388 INFO    MainThread:465542 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-08 14:15:37,403 INFO    MainThread:465542 [wandb_run.py:_footer_sync_info():3895] logging synced files
