2024-04-08 08:48:54,469 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-08 08:48:54,470 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Configure stats pid to 465542
2024-04-08 08:48:54,471 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Loading settings from /home/russellsb/.config/wandb/settings
2024-04-08 08:48:54,472 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/settings
2024-04-08 08:48:54,472 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-08 08:48:54,473 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-08 08:48:54,474 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-08 08:48:54,474 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-08 08:48:54,476 INFO    MainThread:465542 [wandb_init.py:_log_setup():521] Logging user logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240408_084854-esw1edhr/logs/debug.log
2024-04-08 08:48:54,477 INFO    MainThread:465542 [wandb_init.py:_log_setup():522] Logging internal logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240408_084854-esw1edhr/logs/debug-internal.log
2024-04-08 08:48:54,477 INFO    MainThread:465542 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f42c810fca0>
2024-04-08 08:48:54,478 INFO    MainThread:465542 [wandb_init.py:init():561] calling init triggers
2024-04-08 08:48:54,478 INFO    MainThread:465542 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-08 08:48:54,479 INFO    MainThread:465542 [wandb_init.py:init():586] re-initializing run, found existing run on stack: 4cticswf
2024-04-08 08:48:54,482 INFO    MainThread:465542 [wandb_run.py:_finish():2064] finishing run russellsb/x-ray-chest-disease-classification/4cticswf
2024-04-08 08:48:54,482 INFO    MainThread:465542 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-08 08:48:54,483 INFO    MainThread:465542 [wandb_run.py:_restore():2287] restore
2024-04-08 08:48:54,484 INFO    MainThread:465542 [wandb_run.py:_restore():2293] restore done
2024-04-08 08:49:01,027 INFO    MainThread:465542 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-08 08:49:01,028 INFO    MainThread:465542 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-08 08:49:01,042 INFO    MainThread:465542 [wandb_run.py:_footer_sync_info():3895] logging synced files
2024-04-08 08:49:01,077 INFO    MainThread:465542 [wandb_init.py:init():611] starting backend
2024-04-08 08:49:01,078 INFO    MainThread:465542 [wandb_init.py:init():615] setting up manager
2024-04-08 08:49:01,084 INFO    MainThread:465542 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-08 08:49:01,085 INFO    MainThread:465542 [wandb_init.py:init():623] backend started and connected
2024-04-08 08:49:01,099 INFO    MainThread:465542 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-08 08:49:01,099 INFO    MainThread:465542 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-08 08:49:01,100 INFO    MainThread:465542 [wandb_init.py:init():715] updated telemetry
2024-04-08 08:49:01,118 INFO    MainThread:465542 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-08 08:49:02,506 INFO    MainThread:465542 [wandb_run.py:_on_init():2357] communicating current version
2024-04-08 08:49:02,607 INFO    MainThread:465542 [wandb_run.py:_on_init():2366] got version response 
2024-04-08 08:49:02,607 INFO    MainThread:465542 [wandb_init.py:init():799] starting run threads in backend
2024-04-08 08:49:02,747 INFO    MainThread:465542 [wandb_run.py:_console_start():2335] atexit reg
2024-04-08 08:49:02,748 INFO    MainThread:465542 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-08 08:49:02,748 INFO    MainThread:465542 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-08 08:49:02,749 INFO    MainThread:465542 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-08 08:49:02,750 INFO    MainThread:465542 [wandb_init.py:init():842] run started, returning control to user process
2024-04-08 08:49:23,368 INFO    MainThread:465542 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-08 08:49:23,368 INFO    MainThread:465542 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-08 08:49:25,742 INFO    MainThread:465542 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-08 08:49:25,787 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-08 08:49:25,787 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Configure stats pid to 465542
2024-04-08 08:49:25,788 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Loading settings from /home/russellsb/.config/wandb/settings
2024-04-08 08:49:25,789 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/settings
2024-04-08 08:49:25,789 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-08 08:49:25,790 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-08 08:49:25,791 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-08 08:49:25,792 INFO    MainThread:465542 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-08 08:49:25,793 INFO    MainThread:465542 [wandb_init.py:_log_setup():521] Logging user logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240408_084925-tlb8f8vp/logs/debug.log
2024-04-08 08:49:25,794 INFO    MainThread:465542 [wandb_init.py:_log_setup():522] Logging internal logs to /mnt/c/Users/rsamm/root/repos/Data Science for Business Package/4. Operations Department/wandb/run-20240408_084925-tlb8f8vp/logs/debug-internal.log
2024-04-08 08:49:25,795 INFO    MainThread:465542 [wandb_init.py:init():561] calling init triggers
2024-04-08 08:49:25,795 INFO    MainThread:465542 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-08 08:49:25,796 INFO    MainThread:465542 [wandb_init.py:init():586] re-initializing run, found existing run on stack: esw1edhr
2024-04-08 08:49:25,800 INFO    MainThread:465542 [wandb_run.py:_finish():2064] finishing run russellsb/x-ray-chest-disease-classification/esw1edhr
2024-04-08 08:49:25,802 ERROR   MainThread:465542 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-08 08:49:25,802 INFO    MainThread:465542 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-08 08:49:25,803 INFO    MainThread:465542 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-04-08 08:49:25,804 INFO    MainThread:465542 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-08 08:49:25,805 INFO    MainThread:465542 [wandb_run.py:_restore():2287] restore
2024-04-08 08:49:25,806 INFO    MainThread:465542 [wandb_run.py:_restore():2293] restore done
2024-04-08 08:49:31,765 INFO    MainThread:465542 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-08 08:49:31,766 INFO    MainThread:465542 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-08 08:49:31,778 INFO    MainThread:465542 [wandb_run.py:_footer_sync_info():3895] logging synced files
